histogram_positive_slope
IDEAS-NCBR-Computer-Graphics-Group/generative-inverse-heat-dissipation pull request #18
Opened 2024-10-08 11:55 UTC by JakubMeixner

2024-10-08 12:13 UTC, ggruszczynski requested changes

2024-10-08 12:28 UTC, ggruszczynski commented on numerical_solvers/visualization/histogram_turbulence.py
ok, so lets leave it as it is

2024-10-08 16:45 UTC, JakubMeixner commented
added  linear positive increasing spectrum in file /home/computergraphics/Documents/jjmeixner/generative-inverse-heat-dissipation/numerical_solvers/solvers/1D_spectral_turbulence_generator.py


![image](https://github.com/user-attachments/assets/eea9ef89-f57b-48dd-a9dc-50b01a7ba624)

2024-10-11 08:00 UTC, ggruszczynski commented on output/iteration_0.jpg
remove img

2024-10-11 13:23 UTC, ggruszczynski approved these changes
lgtm (looks good to me)

2024-10-11 13:23 UTC, merged