Std_turbulece_generator
IDEAS-NCBR-Computer-Graphics-Group/generative-inverse-heat-dissipation pull request #21
Opened 2024-10-14 12:59 UTC by JakubMeixner

2024-10-14 14:28 UTC, ggruszczynski requested changes

2024-10-14 14:28 UTC, ggruszczynski commented on numerical_solvers/solvers/SpectralTurbulenceGenerator.py
> +        v_hat = self.std_dev * self.amplitude * t.exp(1j * (self.phase_v + self.omega * time))
@JakubMeixner this is weird
```
u_hat = self.std_dev * self.amplitude * t.exp(1j * (self.phase_u + self.omega * time))
... 
u *= self.std_dev / t.std(u) 
```

do we really need to multply by `self.std_dev` twice?
After the first multiplication the result is divided by `t.std(u) ` anyway.

2024-10-14 15:04 UTC, JakubMeixner reviewed
will be done

2024-10-14 15:17 UTC, JakubMeixner reviewed
changed

2024-10-15 07:06 UTC, JakubMeixner reviewed
to be accepted

2024-10-15 08:26 UTC, merged